### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackcalls#8]
The Slack API docs have [descriptions of 4 primary tiers of rate limits](https://api.slack.com/docs/rate-limits) (plus some special cases), and then each method lists its limit. I did something yesterday that hit the limit, and that was annoying. I knew it would probably take a long time, but I had to program around the limit myself. I realized... we can build that in!

As far as I've found, the limits are (mostly) per method, so this technique should keep Slack happy most of the time.

We could add an optional argument to `post_slack`, something like "rate_limit", an integer number of calls per minute. If it's included, we add information to the `.slack` environment about that method's rate limit, what minute we're "in" for this method, and how many calls the user has made to it this minute. If the limit has been reached for the current minute, we sleep until the following minute, reset the count, and reset the minute. It's better for us to build this in directly, because we can increment the count properly if we make multiple calls in the course of a single function call (ie, if we use `paginate_`).

For any methods we implement directly, we can include the `rate_limit`, but we can leave it as a parameter that users can adjust (by calling `post_slack` directly) if they want to try to burst and that sort of thing.

If that all sounds reasonable, I'll implement this (and remove the hacked version from my code).

**Comment by yonicd** [comment]
That makes sense. I saw someone else not long ago bump up against that too.
