### ISSUE TITLE
GHA to keep slackr-test in sync with tests

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackcalls#9]
Slack now only shows the last 90 days of messages, rather than the last 10000 messages. Therefore, messages that are expected for tests "fade away" every 90 days.

Let's add a GHA that resets the slack-r channel every so often (probably more frequent than 90 days to protect a little against tweaks in that policy). In theory it should be straightforward to clear out messages and recreate them (using slackcalls). Of course, if the tests start failing, this updater will likely also fail, but that will give us an early alert, so probably a win-win.

**Comment by yonicd** [comment]
Makes sense. Thanks for catching that.

**Comment by jonthegeek** [comment]
I'm looking into implementing this as part of the standard test suite in slackposts. That way we'll reset the channel every time we run tests in that package, and we can trigger the slackposts tests (once I get the triggers working again) if any package encounters problems with the test channel.

**Comment by jonthegeek** [comment]
Implemented in slackposts.
